bu const fs = require('fs');
const path = require('path');

function stripJsonc(content) {
  content = content.replace(/\/\*[\s\S]*?\*\//g, '');
  content = content.replace(/(^|\n)\s*\/\/.*(?=\n|$)/g, '\n');
  return content;
}

const cfgPath = path.resolve(__dirname, '..', 'wrangler.jsonc');
if (!fs.existsSync(cfgPath)) {
  console.error('wrangler.jsonc not found at', cfgPath);
  process.exit(0);
}

const raw = fs.readFileSync(cfgPath, 'utf8');
let parsed;
try {
  parsed = JSON.parse(stripJsonc(raw));
} catch (e) {
  console.error('Failed to parse wrangler.jsonc — proceeding without creating placeholder');
  process.exit(0);
}

const main = parsed.main;
if (!main) process.exit(0);

const mainPath = path.resolve(path.dirname(cfgPath), main);
const dir = path.dirname(mainPath);
if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

if (fs.existsSync(mainPath) && fs.statSync(mainPath).size > 0) {
  console.log('Entry file already exists:', mainPath);
  process.exit(0);
}

const placeholder = "// Placeholder entry generated by scripts/ensure-entry.cjs\nexport const _placeholder = true;\n";
fs.writeFileSync(mainPath, placeholder, 'utf8');
console.log('Wrote placeholder entry file at', mainPath);
