#!/usr/bin/env node
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

function stripJsonc(content) {
  // remove /**/ comments
  content = content.replace(/\/\*[\s\S]*?\*\//g, '');
  // remove // comments
  content = content.replace(/(^|\n)\s*\/\/.*(?=\n|$)/g, '\n');
  return content;
}

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const cfgPath = path.resolve(__dirname, '..', 'wrangler.jsonc');
if (!fs.existsSync(cfgPath)) {
  console.error('wrangler.jsonc not found at', cfgPath);
  process.exit(0);
}

const raw = fs.readFileSync(cfgPath, 'utf8');
let parsed;
try {
  parsed = JSON.parse(stripJsonc(raw));
} catch (e) {
  console.error('Failed to parse wrangler.jsonc — proceeding without creating placeholder');
  process.exit(0);
}

const main = parsed.main;
if (!main) {
  // nothing to do
  process.exit(0);
}

const mainPath = path.resolve(path.dirname(cfgPath), main);
const dir = path.dirname(mainPath);
if (!fs.existsSync(dir)) {
  fs.mkdirSync(dir, { recursive: true });
}

// If file exists and non-empty, leave it
if (fs.existsSync(mainPath) && fs.statSync(mainPath).size > 0) {
  console.log('Entry file already exists:', mainPath);
  process.exit(0);
}

// Write a minimal ESM placeholder that will be replaced by the real build output
const placeholder = `// Placeholder entry generated by scripts/ensure-entry.js\nexport const _placeholder = true;\n`;

fs.writeFileSync(mainPath, placeholder, 'utf8');
console.log('Wrote placeholder entry file at', mainPath);
