/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AppRouteImport } from './routes/app'
import { Route as ModelSnapRouteImport } from './routes/ModelSnap'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SharedTokenRouteImport } from './routes/shared.$token'
import { Route as FileFileIdRouteImport } from './routes/file.$fileId'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiBlogRouteImport } from './routes/api/blog'
import { Route as AdminAuthorsRouteImport } from './routes/admin.authors'
import { Route as ApiSharedTokenRouteImport } from './routes/api/shared.$token'
import { Route as ApiFilesVersionsRouteImport } from './routes/api/files/versions'
import { Route as ApiFilesUploadRouteImport } from './routes/api/files/upload'
import { Route as ApiFilesTrashRouteImport } from './routes/api/files/trash'
import { Route as ApiFilesThumbnailRouteImport } from './routes/api/files/thumbnail'
import { Route as ApiFilesStarredRouteImport } from './routes/api/files/starred'
import { Route as ApiFilesStarRouteImport } from './routes/api/files/star'
import { Route as ApiFilesSharedWithMeRouteImport } from './routes/api/files/shared-with-me'
import { Route as ApiFilesShareRouteImport } from './routes/api/files/share'
import { Route as ApiFilesRenameRouteImport } from './routes/api/files/rename'
import { Route as ApiFilesRecentRouteImport } from './routes/api/files/recent'
import { Route as ApiFilesPresignedUploadRouteImport } from './routes/api/files/presigned-upload'
import { Route as ApiFilesListRouteImport } from './routes/api/files/list'
import { Route as ApiFilesDownloadRouteImport } from './routes/api/files/download'
import { Route as ApiFilesDetailRouteImport } from './routes/api/files/detail'
import { Route as ApiFilesCompleteUploadRouteImport } from './routes/api/files/complete-upload'
import { Route as ApiFilesCommentsRouteImport } from './routes/api/files/comments'
import { Route as ApiBlogUploadRouteImport } from './routes/api/blog.upload'
import { Route as ApiBlogIdRouteImport } from './routes/api/blog.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminUserFilesRouteImport } from './routes/api/admin/user-files'
import { Route as ApiAdminSurveyRouteImport } from './routes/api/admin/survey'
import { Route as ApiAdminStorageStatsRouteImport } from './routes/api/admin/storage-stats'
import { Route as ApiAdminAuthorsRouteImport } from './routes/api/admin/authors'
import { Route as ApiAdminActivitiesRouteImport } from './routes/api/admin/activities'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as AdminBlogNewRouteImport } from './routes/admin.blog.new'
import { Route as AdminBlogPostIdRouteImport } from './routes/admin.blog.$postId'
import { Route as ApiBlogSlugSlugRouteImport } from './routes/api/blog.slug.$slug'
import { Route as ApiBlogImageKeyRouteImport } from './routes/api/blog.image.$key'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelSnapRoute = ModelSnapRouteImport.update({
  id: '/ModelSnap',
  path: '/ModelSnap',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FileFileIdRoute = FileFileIdRouteImport.update({
  id: '/file/$fileId',
  path: '/file/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiBlogRoute = ApiBlogRouteImport.update({
  id: '/api/blog',
  path: '/api/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthorsRoute = AdminAuthorsRouteImport.update({
  id: '/admin/authors',
  path: '/admin/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSharedTokenRoute = ApiSharedTokenRouteImport.update({
  id: '/api/shared/$token',
  path: '/api/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesVersionsRoute = ApiFilesVersionsRouteImport.update({
  id: '/api/files/versions',
  path: '/api/files/versions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesUploadRoute = ApiFilesUploadRouteImport.update({
  id: '/api/files/upload',
  path: '/api/files/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesTrashRoute = ApiFilesTrashRouteImport.update({
  id: '/api/files/trash',
  path: '/api/files/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesThumbnailRoute = ApiFilesThumbnailRouteImport.update({
  id: '/api/files/thumbnail',
  path: '/api/files/thumbnail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesStarredRoute = ApiFilesStarredRouteImport.update({
  id: '/api/files/starred',
  path: '/api/files/starred',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesStarRoute = ApiFilesStarRouteImport.update({
  id: '/api/files/star',
  path: '/api/files/star',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesSharedWithMeRoute = ApiFilesSharedWithMeRouteImport.update({
  id: '/api/files/shared-with-me',
  path: '/api/files/shared-with-me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesShareRoute = ApiFilesShareRouteImport.update({
  id: '/api/files/share',
  path: '/api/files/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRenameRoute = ApiFilesRenameRouteImport.update({
  id: '/api/files/rename',
  path: '/api/files/rename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRecentRoute = ApiFilesRecentRouteImport.update({
  id: '/api/files/recent',
  path: '/api/files/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesPresignedUploadRoute = ApiFilesPresignedUploadRouteImport.update({
  id: '/api/files/presigned-upload',
  path: '/api/files/presigned-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesListRoute = ApiFilesListRouteImport.update({
  id: '/api/files/list',
  path: '/api/files/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesDownloadRoute = ApiFilesDownloadRouteImport.update({
  id: '/api/files/download',
  path: '/api/files/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesDetailRoute = ApiFilesDetailRouteImport.update({
  id: '/api/files/detail',
  path: '/api/files/detail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesCompleteUploadRoute = ApiFilesCompleteUploadRouteImport.update({
  id: '/api/files/complete-upload',
  path: '/api/files/complete-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesCommentsRoute = ApiFilesCommentsRouteImport.update({
  id: '/api/files/comments',
  path: '/api/files/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogUploadRoute = ApiBlogUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ApiBlogRoute,
} as any)
const ApiBlogIdRoute = ApiBlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiBlogRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUserFilesRoute = ApiAdminUserFilesRouteImport.update({
  id: '/api/admin/user-files',
  path: '/api/admin/user-files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSurveyRoute = ApiAdminSurveyRouteImport.update({
  id: '/api/admin/survey',
  path: '/api/admin/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStorageStatsRoute = ApiAdminStorageStatsRouteImport.update({
  id: '/api/admin/storage-stats',
  path: '/api/admin/storage-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthorsRoute = ApiAdminAuthorsRouteImport.update({
  id: '/api/admin/authors',
  path: '/api/admin/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminActivitiesRoute = ApiAdminActivitiesRouteImport.update({
  id: '/api/admin/activities',
  path: '/api/admin/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/admin/users/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/admin/blog/new',
  path: '/admin/blog/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogPostIdRoute = AdminBlogPostIdRouteImport.update({
  id: '/admin/blog/$postId',
  path: '/admin/blog/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogSlugSlugRoute = ApiBlogSlugSlugRouteImport.update({
  id: '/slug/$slug',
  path: '/slug/$slug',
  getParentRoute: () => ApiBlogRoute,
} as any)
const ApiBlogImageKeyRoute = ApiBlogImageKeyRouteImport.update({
  id: '/image/$key',
  path: '/image/$key',
  getParentRoute: () => ApiBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ModelSnap': typeof ModelSnapRoute
  '/app': typeof AppRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/authors': typeof AdminAuthorsRoute
  '/api/blog': typeof ApiBlogRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/file/$fileId': typeof FileFileIdRoute
  '/shared/$token': typeof SharedTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blog/$postId': typeof AdminBlogPostIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/admin/activities': typeof ApiAdminActivitiesRoute
  '/api/admin/authors': typeof ApiAdminAuthorsRoute
  '/api/admin/storage-stats': typeof ApiAdminStorageStatsRoute
  '/api/admin/survey': typeof ApiAdminSurveyRoute
  '/api/admin/user-files': typeof ApiAdminUserFilesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blog/$id': typeof ApiBlogIdRoute
  '/api/blog/upload': typeof ApiBlogUploadRoute
  '/api/files/comments': typeof ApiFilesCommentsRoute
  '/api/files/complete-upload': typeof ApiFilesCompleteUploadRoute
  '/api/files/detail': typeof ApiFilesDetailRoute
  '/api/files/download': typeof ApiFilesDownloadRoute
  '/api/files/list': typeof ApiFilesListRoute
  '/api/files/presigned-upload': typeof ApiFilesPresignedUploadRoute
  '/api/files/recent': typeof ApiFilesRecentRoute
  '/api/files/rename': typeof ApiFilesRenameRoute
  '/api/files/share': typeof ApiFilesShareRoute
  '/api/files/shared-with-me': typeof ApiFilesSharedWithMeRoute
  '/api/files/star': typeof ApiFilesStarRoute
  '/api/files/starred': typeof ApiFilesStarredRoute
  '/api/files/thumbnail': typeof ApiFilesThumbnailRoute
  '/api/files/trash': typeof ApiFilesTrashRoute
  '/api/files/upload': typeof ApiFilesUploadRoute
  '/api/files/versions': typeof ApiFilesVersionsRoute
  '/api/shared/$token': typeof ApiSharedTokenRoute
  '/api/blog/image/$key': typeof ApiBlogImageKeyRoute
  '/api/blog/slug/$slug': typeof ApiBlogSlugSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ModelSnap': typeof ModelSnapRoute
  '/app': typeof AppRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/authors': typeof AdminAuthorsRoute
  '/api/blog': typeof ApiBlogRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/file/$fileId': typeof FileFileIdRoute
  '/shared/$token': typeof SharedTokenRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/blog/$postId': typeof AdminBlogPostIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/admin/activities': typeof ApiAdminActivitiesRoute
  '/api/admin/authors': typeof ApiAdminAuthorsRoute
  '/api/admin/storage-stats': typeof ApiAdminStorageStatsRoute
  '/api/admin/survey': typeof ApiAdminSurveyRoute
  '/api/admin/user-files': typeof ApiAdminUserFilesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blog/$id': typeof ApiBlogIdRoute
  '/api/blog/upload': typeof ApiBlogUploadRoute
  '/api/files/comments': typeof ApiFilesCommentsRoute
  '/api/files/complete-upload': typeof ApiFilesCompleteUploadRoute
  '/api/files/detail': typeof ApiFilesDetailRoute
  '/api/files/download': typeof ApiFilesDownloadRoute
  '/api/files/list': typeof ApiFilesListRoute
  '/api/files/presigned-upload': typeof ApiFilesPresignedUploadRoute
  '/api/files/recent': typeof ApiFilesRecentRoute
  '/api/files/rename': typeof ApiFilesRenameRoute
  '/api/files/share': typeof ApiFilesShareRoute
  '/api/files/shared-with-me': typeof ApiFilesSharedWithMeRoute
  '/api/files/star': typeof ApiFilesStarRoute
  '/api/files/starred': typeof ApiFilesStarredRoute
  '/api/files/thumbnail': typeof ApiFilesThumbnailRoute
  '/api/files/trash': typeof ApiFilesTrashRoute
  '/api/files/upload': typeof ApiFilesUploadRoute
  '/api/files/versions': typeof ApiFilesVersionsRoute
  '/api/shared/$token': typeof ApiSharedTokenRoute
  '/api/blog/image/$key': typeof ApiBlogImageKeyRoute
  '/api/blog/slug/$slug': typeof ApiBlogSlugSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ModelSnap': typeof ModelSnapRoute
  '/app': typeof AppRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/authors': typeof AdminAuthorsRoute
  '/api/blog': typeof ApiBlogRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/file/$fileId': typeof FileFileIdRoute
  '/shared/$token': typeof SharedTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blog/$postId': typeof AdminBlogPostIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/admin/activities': typeof ApiAdminActivitiesRoute
  '/api/admin/authors': typeof ApiAdminAuthorsRoute
  '/api/admin/storage-stats': typeof ApiAdminStorageStatsRoute
  '/api/admin/survey': typeof ApiAdminSurveyRoute
  '/api/admin/user-files': typeof ApiAdminUserFilesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blog/$id': typeof ApiBlogIdRoute
  '/api/blog/upload': typeof ApiBlogUploadRoute
  '/api/files/comments': typeof ApiFilesCommentsRoute
  '/api/files/complete-upload': typeof ApiFilesCompleteUploadRoute
  '/api/files/detail': typeof ApiFilesDetailRoute
  '/api/files/download': typeof ApiFilesDownloadRoute
  '/api/files/list': typeof ApiFilesListRoute
  '/api/files/presigned-upload': typeof ApiFilesPresignedUploadRoute
  '/api/files/recent': typeof ApiFilesRecentRoute
  '/api/files/rename': typeof ApiFilesRenameRoute
  '/api/files/share': typeof ApiFilesShareRoute
  '/api/files/shared-with-me': typeof ApiFilesSharedWithMeRoute
  '/api/files/star': typeof ApiFilesStarRoute
  '/api/files/starred': typeof ApiFilesStarredRoute
  '/api/files/thumbnail': typeof ApiFilesThumbnailRoute
  '/api/files/trash': typeof ApiFilesTrashRoute
  '/api/files/upload': typeof ApiFilesUploadRoute
  '/api/files/versions': typeof ApiFilesVersionsRoute
  '/api/shared/$token': typeof ApiSharedTokenRoute
  '/api/blog/image/$key': typeof ApiBlogImageKeyRoute
  '/api/blog/slug/$slug': typeof ApiBlogSlugSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ModelSnap'
    | '/app'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/verify-email'
    | '/admin/authors'
    | '/api/blog'
    | '/blog/$slug'
    | '/file/$fileId'
    | '/shared/$token'
    | '/admin/'
    | '/blog/'
    | '/admin/blog/$postId'
    | '/admin/blog/new'
    | '/admin/users/$userId'
    | '/api/admin/activities'
    | '/api/admin/authors'
    | '/api/admin/storage-stats'
    | '/api/admin/survey'
    | '/api/admin/user-files'
    | '/api/auth/$'
    | '/api/blog/$id'
    | '/api/blog/upload'
    | '/api/files/comments'
    | '/api/files/complete-upload'
    | '/api/files/detail'
    | '/api/files/download'
    | '/api/files/list'
    | '/api/files/presigned-upload'
    | '/api/files/recent'
    | '/api/files/rename'
    | '/api/files/share'
    | '/api/files/shared-with-me'
    | '/api/files/star'
    | '/api/files/starred'
    | '/api/files/thumbnail'
    | '/api/files/trash'
    | '/api/files/upload'
    | '/api/files/versions'
    | '/api/shared/$token'
    | '/api/blog/image/$key'
    | '/api/blog/slug/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ModelSnap'
    | '/app'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/verify-email'
    | '/admin/authors'
    | '/api/blog'
    | '/blog/$slug'
    | '/file/$fileId'
    | '/shared/$token'
    | '/admin'
    | '/blog'
    | '/admin/blog/$postId'
    | '/admin/blog/new'
    | '/admin/users/$userId'
    | '/api/admin/activities'
    | '/api/admin/authors'
    | '/api/admin/storage-stats'
    | '/api/admin/survey'
    | '/api/admin/user-files'
    | '/api/auth/$'
    | '/api/blog/$id'
    | '/api/blog/upload'
    | '/api/files/comments'
    | '/api/files/complete-upload'
    | '/api/files/detail'
    | '/api/files/download'
    | '/api/files/list'
    | '/api/files/presigned-upload'
    | '/api/files/recent'
    | '/api/files/rename'
    | '/api/files/share'
    | '/api/files/shared-with-me'
    | '/api/files/star'
    | '/api/files/starred'
    | '/api/files/thumbnail'
    | '/api/files/trash'
    | '/api/files/upload'
    | '/api/files/versions'
    | '/api/shared/$token'
    | '/api/blog/image/$key'
    | '/api/blog/slug/$slug'
  id:
    | '__root__'
    | '/'
    | '/ModelSnap'
    | '/app'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/verify-email'
    | '/admin/authors'
    | '/api/blog'
    | '/blog/$slug'
    | '/file/$fileId'
    | '/shared/$token'
    | '/admin/'
    | '/blog/'
    | '/admin/blog/$postId'
    | '/admin/blog/new'
    | '/admin/users/$userId'
    | '/api/admin/activities'
    | '/api/admin/authors'
    | '/api/admin/storage-stats'
    | '/api/admin/survey'
    | '/api/admin/user-files'
    | '/api/auth/$'
    | '/api/blog/$id'
    | '/api/blog/upload'
    | '/api/files/comments'
    | '/api/files/complete-upload'
    | '/api/files/detail'
    | '/api/files/download'
    | '/api/files/list'
    | '/api/files/presigned-upload'
    | '/api/files/recent'
    | '/api/files/rename'
    | '/api/files/share'
    | '/api/files/shared-with-me'
    | '/api/files/star'
    | '/api/files/starred'
    | '/api/files/thumbnail'
    | '/api/files/trash'
    | '/api/files/upload'
    | '/api/files/versions'
    | '/api/shared/$token'
    | '/api/blog/image/$key'
    | '/api/blog/slug/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModelSnapRoute: typeof ModelSnapRoute
  AppRoute: typeof AppRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminAuthorsRoute: typeof AdminAuthorsRoute
  ApiBlogRoute: typeof ApiBlogRouteWithChildren
  FileFileIdRoute: typeof FileFileIdRoute
  SharedTokenRoute: typeof SharedTokenRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogPostIdRoute: typeof AdminBlogPostIdRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  ApiAdminActivitiesRoute: typeof ApiAdminActivitiesRoute
  ApiAdminAuthorsRoute: typeof ApiAdminAuthorsRoute
  ApiAdminStorageStatsRoute: typeof ApiAdminStorageStatsRoute
  ApiAdminSurveyRoute: typeof ApiAdminSurveyRoute
  ApiAdminUserFilesRoute: typeof ApiAdminUserFilesRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFilesCommentsRoute: typeof ApiFilesCommentsRoute
  ApiFilesCompleteUploadRoute: typeof ApiFilesCompleteUploadRoute
  ApiFilesDetailRoute: typeof ApiFilesDetailRoute
  ApiFilesDownloadRoute: typeof ApiFilesDownloadRoute
  ApiFilesListRoute: typeof ApiFilesListRoute
  ApiFilesPresignedUploadRoute: typeof ApiFilesPresignedUploadRoute
  ApiFilesRecentRoute: typeof ApiFilesRecentRoute
  ApiFilesRenameRoute: typeof ApiFilesRenameRoute
  ApiFilesShareRoute: typeof ApiFilesShareRoute
  ApiFilesSharedWithMeRoute: typeof ApiFilesSharedWithMeRoute
  ApiFilesStarRoute: typeof ApiFilesStarRoute
  ApiFilesStarredRoute: typeof ApiFilesStarredRoute
  ApiFilesThumbnailRoute: typeof ApiFilesThumbnailRoute
  ApiFilesTrashRoute: typeof ApiFilesTrashRoute
  ApiFilesUploadRoute: typeof ApiFilesUploadRoute
  ApiFilesVersionsRoute: typeof ApiFilesVersionsRoute
  ApiSharedTokenRoute: typeof ApiSharedTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ModelSnap': {
      id: '/ModelSnap'
      path: '/ModelSnap'
      fullPath: '/ModelSnap'
      preLoaderRoute: typeof ModelSnapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file/$fileId': {
      id: '/file/$fileId'
      path: '/file/$fileId'
      fullPath: '/file/$fileId'
      preLoaderRoute: typeof FileFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/blog': {
      id: '/api/blog'
      path: '/api/blog'
      fullPath: '/api/blog'
      preLoaderRoute: typeof ApiBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/authors': {
      id: '/admin/authors'
      path: '/admin/authors'
      fullPath: '/admin/authors'
      preLoaderRoute: typeof AdminAuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shared/$token': {
      id: '/api/shared/$token'
      path: '/api/shared/$token'
      fullPath: '/api/shared/$token'
      preLoaderRoute: typeof ApiSharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/versions': {
      id: '/api/files/versions'
      path: '/api/files/versions'
      fullPath: '/api/files/versions'
      preLoaderRoute: typeof ApiFilesVersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/upload': {
      id: '/api/files/upload'
      path: '/api/files/upload'
      fullPath: '/api/files/upload'
      preLoaderRoute: typeof ApiFilesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/trash': {
      id: '/api/files/trash'
      path: '/api/files/trash'
      fullPath: '/api/files/trash'
      preLoaderRoute: typeof ApiFilesTrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/thumbnail': {
      id: '/api/files/thumbnail'
      path: '/api/files/thumbnail'
      fullPath: '/api/files/thumbnail'
      preLoaderRoute: typeof ApiFilesThumbnailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/starred': {
      id: '/api/files/starred'
      path: '/api/files/starred'
      fullPath: '/api/files/starred'
      preLoaderRoute: typeof ApiFilesStarredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/star': {
      id: '/api/files/star'
      path: '/api/files/star'
      fullPath: '/api/files/star'
      preLoaderRoute: typeof ApiFilesStarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/shared-with-me': {
      id: '/api/files/shared-with-me'
      path: '/api/files/shared-with-me'
      fullPath: '/api/files/shared-with-me'
      preLoaderRoute: typeof ApiFilesSharedWithMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/share': {
      id: '/api/files/share'
      path: '/api/files/share'
      fullPath: '/api/files/share'
      preLoaderRoute: typeof ApiFilesShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/rename': {
      id: '/api/files/rename'
      path: '/api/files/rename'
      fullPath: '/api/files/rename'
      preLoaderRoute: typeof ApiFilesRenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/recent': {
      id: '/api/files/recent'
      path: '/api/files/recent'
      fullPath: '/api/files/recent'
      preLoaderRoute: typeof ApiFilesRecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/presigned-upload': {
      id: '/api/files/presigned-upload'
      path: '/api/files/presigned-upload'
      fullPath: '/api/files/presigned-upload'
      preLoaderRoute: typeof ApiFilesPresignedUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/list': {
      id: '/api/files/list'
      path: '/api/files/list'
      fullPath: '/api/files/list'
      preLoaderRoute: typeof ApiFilesListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/download': {
      id: '/api/files/download'
      path: '/api/files/download'
      fullPath: '/api/files/download'
      preLoaderRoute: typeof ApiFilesDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/detail': {
      id: '/api/files/detail'
      path: '/api/files/detail'
      fullPath: '/api/files/detail'
      preLoaderRoute: typeof ApiFilesDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/complete-upload': {
      id: '/api/files/complete-upload'
      path: '/api/files/complete-upload'
      fullPath: '/api/files/complete-upload'
      preLoaderRoute: typeof ApiFilesCompleteUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/comments': {
      id: '/api/files/comments'
      path: '/api/files/comments'
      fullPath: '/api/files/comments'
      preLoaderRoute: typeof ApiFilesCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/upload': {
      id: '/api/blog/upload'
      path: '/upload'
      fullPath: '/api/blog/upload'
      preLoaderRoute: typeof ApiBlogUploadRouteImport
      parentRoute: typeof ApiBlogRoute
    }
    '/api/blog/$id': {
      id: '/api/blog/$id'
      path: '/$id'
      fullPath: '/api/blog/$id'
      preLoaderRoute: typeof ApiBlogIdRouteImport
      parentRoute: typeof ApiBlogRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/user-files': {
      id: '/api/admin/user-files'
      path: '/api/admin/user-files'
      fullPath: '/api/admin/user-files'
      preLoaderRoute: typeof ApiAdminUserFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/survey': {
      id: '/api/admin/survey'
      path: '/api/admin/survey'
      fullPath: '/api/admin/survey'
      preLoaderRoute: typeof ApiAdminSurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/storage-stats': {
      id: '/api/admin/storage-stats'
      path: '/api/admin/storage-stats'
      fullPath: '/api/admin/storage-stats'
      preLoaderRoute: typeof ApiAdminStorageStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/authors': {
      id: '/api/admin/authors'
      path: '/api/admin/authors'
      fullPath: '/api/admin/authors'
      preLoaderRoute: typeof ApiAdminAuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/activities': {
      id: '/api/admin/activities'
      path: '/api/admin/activities'
      fullPath: '/api/admin/activities'
      preLoaderRoute: typeof ApiAdminActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/admin/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/$postId': {
      id: '/admin/blog/$postId'
      path: '/admin/blog/$postId'
      fullPath: '/admin/blog/$postId'
      preLoaderRoute: typeof AdminBlogPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/slug/$slug': {
      id: '/api/blog/slug/$slug'
      path: '/slug/$slug'
      fullPath: '/api/blog/slug/$slug'
      preLoaderRoute: typeof ApiBlogSlugSlugRouteImport
      parentRoute: typeof ApiBlogRoute
    }
    '/api/blog/image/$key': {
      id: '/api/blog/image/$key'
      path: '/image/$key'
      fullPath: '/api/blog/image/$key'
      preLoaderRoute: typeof ApiBlogImageKeyRouteImport
      parentRoute: typeof ApiBlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ApiBlogRouteChildren {
  ApiBlogIdRoute: typeof ApiBlogIdRoute
  ApiBlogUploadRoute: typeof ApiBlogUploadRoute
  ApiBlogImageKeyRoute: typeof ApiBlogImageKeyRoute
  ApiBlogSlugSlugRoute: typeof ApiBlogSlugSlugRoute
}

const ApiBlogRouteChildren: ApiBlogRouteChildren = {
  ApiBlogIdRoute: ApiBlogIdRoute,
  ApiBlogUploadRoute: ApiBlogUploadRoute,
  ApiBlogImageKeyRoute: ApiBlogImageKeyRoute,
  ApiBlogSlugSlugRoute: ApiBlogSlugSlugRoute,
}

const ApiBlogRouteWithChildren =
  ApiBlogRoute._addFileChildren(ApiBlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModelSnapRoute: ModelSnapRoute,
  AppRoute: AppRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminAuthorsRoute: AdminAuthorsRoute,
  ApiBlogRoute: ApiBlogRouteWithChildren,
  FileFileIdRoute: FileFileIdRoute,
  SharedTokenRoute: SharedTokenRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogPostIdRoute: AdminBlogPostIdRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  ApiAdminActivitiesRoute: ApiAdminActivitiesRoute,
  ApiAdminAuthorsRoute: ApiAdminAuthorsRoute,
  ApiAdminStorageStatsRoute: ApiAdminStorageStatsRoute,
  ApiAdminSurveyRoute: ApiAdminSurveyRoute,
  ApiAdminUserFilesRoute: ApiAdminUserFilesRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFilesCommentsRoute: ApiFilesCommentsRoute,
  ApiFilesCompleteUploadRoute: ApiFilesCompleteUploadRoute,
  ApiFilesDetailRoute: ApiFilesDetailRoute,
  ApiFilesDownloadRoute: ApiFilesDownloadRoute,
  ApiFilesListRoute: ApiFilesListRoute,
  ApiFilesPresignedUploadRoute: ApiFilesPresignedUploadRoute,
  ApiFilesRecentRoute: ApiFilesRecentRoute,
  ApiFilesRenameRoute: ApiFilesRenameRoute,
  ApiFilesShareRoute: ApiFilesShareRoute,
  ApiFilesSharedWithMeRoute: ApiFilesSharedWithMeRoute,
  ApiFilesStarRoute: ApiFilesStarRoute,
  ApiFilesStarredRoute: ApiFilesStarredRoute,
  ApiFilesThumbnailRoute: ApiFilesThumbnailRoute,
  ApiFilesTrashRoute: ApiFilesTrashRoute,
  ApiFilesUploadRoute: ApiFilesUploadRoute,
  ApiFilesVersionsRoute: ApiFilesVersionsRoute,
  ApiSharedTokenRoute: ApiSharedTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
